[build]
command = "npm run build"
functions = "netlify/functions"
publish = "build"

# [functions]
# node_bundler = "esbuild"

[dev]
# command = "yarn start" # Command to start your dev server
# port = 8888 # The port that the netlify dev will be accessible on
# publish = "dist" # If you use a _redirect file, provide the path to your static content folder
# targetPort = 3000 # # The port for your application server, framework or site generator
